#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
###############################################################################
#
# TCPPUMP <https://github.com/amartin755/tcppump>
# Copyright (C) 2012-2025 Andreas Martin (netnag@mailbox.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
import argparse
from pathlib import Path
import sys

# PyYAML importieren
try:
    import yaml
except ImportError:
    print("[WARNING] PyYAML not installed. No updates of ctest testcases possible.")
    sys.exit(0)

def has_file_prefix(s: str):
    """Check for file:// prefix and strip it."""
    prefix = "file://"
    if s.startswith(prefix):
        return s[len(prefix):], True
    return s, False

def quote_double(arg: str) -> str:
    arg = arg.replace("\\", "\\\\")
    arg = arg.replace('"', '\\"')
    return f'"{arg}"'

def main():
    parser = argparse.ArgumentParser(description="Generate CTest definitions from YAML")
    parser.add_argument("yaml_file", help="Path to testcases.yaml")
    parser.add_argument("output_file", help="Path to generated_tests.cmake")
    parser.add_argument("--ref-dir", default="${REF_FILES_DIR}", help="Reference files directory variable")
    parser.add_argument("--out-ifc", default="${OUT_IFC}", help="Output interface variable")
    parser.add_argument("--test-tmp", default="${TEST_TMP_DIR}", help="Test temp directory variable")
    args = parser.parse_args()

    yaml_file = Path(args.yaml_file)
    data = yaml.safe_load(yaml_file.read_text())

    defaults = data.get("defaults", [])
    testcases = data.get("testcases", [])

    cmake_lines = [
        "# AUTO-GENERATED FILE - DO NOT EDIT",
        "# Generated by generate_testcases.py",
        ""
    ]

    for tc in testcases:
        name = tc["name"]
        input_params = []

        # input parameters as array (optional)
        if "input" in tc:
            for inp in tc["input"]:
                inp_clean, prefixed = has_file_prefix(inp)
                if prefixed:
                    input_params.append(f"{args.ref_dir}/{inp_clean}")
                else:
                    input_params.append(inp_clean)

        # expected to fail (optional)?
        will_fail = tc.get("will_fail", False)

        # if testcase overwrites "defaults" use them instead -> TEST_PARAMS
        test_params = tc.get("defaults", defaults).copy()

        # send to network? -> add -i parameter to TEST_PARAMS
        live = tc.get("live", False)
        if live:
            test_params += ["-i", args.out_ifc]

        # expected output
        expected_output = tc.get("expected_output")
        pcap_file = None
        out_params = []

        if expected_output is None:
            out_params = ["-F", "hexstream", "-w", "-"]
        else:
            # if !live, set OUT_PARAMS to pcap (file provided) or hexstream
            if live == False:
                expected_output_clean, prefixed = has_file_prefix(expected_output)
                if prefixed:
                    pcap_file = expected_output_clean
                    out_params = ["-F", "pcap", "-w", f"{args.test_tmp}/{name}.pcap"]
                else:
                    out_params = ["-F", "hexstream", "-w", "-"]

        # add additional commandline parameters, if provided
        for opt in tc.get("options", []):
            test_params.append(opt)

        # special handling for debugging
        if expected_output == "TODO":
            out_params = ["-w", f"{args.test_tmp}/{name}.pcap"]

        # create testcase with a dependency to the setup testcase
        cmd = ["tcppump"] + test_params + out_params + input_params
        safe_cmd = " ".join(quote_double(part) for part in cmd)
        cmake_lines.append(f'add_test(NAME "{name}" COMMAND {safe_cmd})')
        cmake_lines.append(f'set_tests_properties("{name}" PROPERTIES FIXTURES_REQUIRED setup)')

        # if output should be compared to a existing pcap file, we create an additional diff testcase
        # Othewise the text output is compared to the expected string (if provided)
        if pcap_file:
            cmake_lines.append(
                f'add_test(NAME "{name}-diff" COMMAND cmake -E compare_files "{args.test_tmp}/{name}.pcap" "{args.ref_dir}/{pcap_file}")'
            )
            # diff testcase must be run after the real testcase
            cmake_lines.append(
                f'set_tests_properties("{name}" PROPERTIES FIXTURES_SETUP "{name}-setup")'
            )
            cmake_lines.append(
                f'set_tests_properties("{name}-diff" PROPERTIES FIXTURES_REQUIRED "{name}-setup")'
            )
        elif expected_output:
            cmake_lines.append(
                f'set_tests_properties("{name}" PROPERTIES PASS_REGULAR_EXPRESSION "{expected_output}")'
            )

        if will_fail:
            cmake_lines.append(
                f'set_tests_properties("{name}" PROPERTIES WILL_FAIL TRUE)'
            )

        cmake_lines.append("")  # blank line between tests

    Path(args.output_file).write_text("\n".join(cmake_lines))
    print(f"[+] Generated CTest definitions: {args.output_file}")


if __name__ == "__main__":
    main()
