# SPDX-License-Identifier: GPL-3.0-only
###############################################################################
#
# TCPPUMP <https://github.com/amartin755/tcppump>
# Copyright (C) 2012-2025 Andreas Martin (netnag@mailbox.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

FROM opensuse/leap:15.6

RUN zypper install -y gcc gcc-c++ clang make cmake git libpcap-devel rpm-build libcap-progs sudo && \
    zypper clean -a

#RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 50 && \
#    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 50 && \
#    update-alternatives --set gcc /usr/bin/gcc-13 && \
#    update-alternatives --set g++ /usr/bin/g++-13

ARG UID=1000
ARG GID=1000
ARG USERNAME=dev

RUN groupadd -g $GID $USERNAME && \
    useradd -m -u $UID -g $GID -s /bin/bash $USERNAME

RUN echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /workdir

USER $USERNAME:$USERNAME

CMD ["/bin/bash"]
